[yandex]
yandex_node ansible_host=158.160.55.125 ansible_user=andrwy

[eu_nodes]
bulgaria_main ansible_host=femboyhooters.kawaiinekos.cfd ansible_user=root bridge_sni=www.microsoft.com is_main=true node_port=3743
;eu_node_2     ansible_host=caffeinated.kawaiinekos.cfd ansible_user=root bridge_sni=drive.google.com node_port=1488
; eu_node_3     ansible_host=150.241.73.20  ansible_user=root bridge_sni=teams.microsoft.com node_port=1488


;aeza ansible_host=194.33.34.251 ansible_user=root ansible_port=22 bridge_sni=google.com node_port=3743 country_code=NL
