---
remnawave_domain: "nekodera.kawaiinekos.cfd"
remnawave_profile_uuid: "7b819d85-3004-480f-99a7-43337e47cbba"
remnawave_inbounds:
  - "d5ee5800-8a71-4f1c-b0b0-a489621c785e"
  - "4e9aa4fd-8b17-4282-acce-4d9ba905d767"
  - "d0a5a963-2bc0-4fff-bf37-56b5e9e40df6"
  - "8b3370a9-c28f-4535-8731-0fbf211cfb2c"

remnawave_api_token: "{{ vault_remnawave_api_token }}"
telemt_users: "{{ vault_telemt_users }}"
